# Generated by Django 2.0.2 on 2020-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VvProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vvpk', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=250)),
                ('premium', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('category', models.CharField(default='', max_length=250)),
                ('timestamp', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='')),
                ('fb_targeting', models.CharField(default='', max_length=250)),
                ('cogs', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('favorite', models.BooleanField(default=False)),
                ('facebook', models.TextField(default='')),
                ('aliexpress1', models.TextField(default='')),
                ('aliexpress2', models.TextField(default='')),
                ('amazon1', models.TextField(default='')),
                ('amazon2', models.TextField(default='')),
                ('competitor_store', models.TextField(default='')),
                ('aliexpress_data', models.TextField(default='')),
                ('images', models.TextField(default='')),
                ('ad_creative', models.TextField(default='')),
            ],
        ),
    ]
