# Generated by Django 2.0.2 on 2020-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvproduct',
            name='comments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vvproduct',
            name='likes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vvproduct',
            name='redirects',
            field=models.FloatField(default=0.0),
        ),
    ]
