# Generated by Django 2.0.2 on 2020-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200321_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvproduct',
            name='fb_url',
            field=models.TextField(default=''),
        ),
    ]
