# Generated by Django 2.1.2 on 2020-03-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vvproduct_fb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvproduct',
            name='facebook',
        ),
    ]
